
version: 2

build:
  image: latest

formats:
    - htmlzip

python:
    version: 3.7
    install:
      - requirements: doc/requirements.txt
      - method: pip
        path: .


sphinx:
    builder: html
    configuration: doc/source/conf.py
    fail_on_warning: false

