name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: []

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.8, 3.8, 3.9, '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.X
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install the package itself
      run: |
          pip install poetry
          poetry install --with dev

    - name: Test with pytest
      run: |
          pytest --cov-report term --cov=colormap

    - name: coveralls
      run: |
        coveralls --service=github
      env:
          GITHUB_TOKEN: ${{ github.token }}

